function solve(input){

    let type = typeof input;
    let arr = typeof [1,2,3,4,5]
    let empty = typeof null;
    let name = typeof "ivan";
    let n = typeof 1;
    let isTrue = typeof false


    console.log(type);
    console.log(arr);
    console.log(empty);
    let unknown = typeof undefined;

    console.log(unknown);
    console.log(name);
    console.log(n);
    console.log(isTrue);
}


solve([1,2,3,4,5])